source 'https://supermarket.chef.io'

#cookbook 'omnibus'

# Uncomment to use the latest version of the Omnibus cookbook from GitHub
# cookbook 'omnibus', github: 'opscode-cookbooks/omnibus'
cookbook 'omnibus', github: 'opscode-cookbooks/omnibus', branch: 'ksubrama/msys2'
cookbook 'build-essential', github: 'opscode-cookbooks/build-essential', branch: 'ksubrama/msys2'
cookbook 'mingw', github: 'opscode-cookbooks/mingw', branch: 'msys2'

group :integration do
  cookbook 'apt',      '~> 2.3'
  cookbook 'freebsd',  '~> 0.1'
  cookbook 'yum-epel', '~> 0.3'
end
